FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGNvcmRvdmEtYXBwLWFwYgpkZXNjcmlwdGlvbjogU2V0cyB1cCBh\
IENvcmRvdmEgQXBwIHJlcHJlc2VudGF0aW9uLgpiaW5kYWJsZTogRmFsc2UKYXN5bmM6IG9wdGlv\
bmFsCnRhZ3M6IAogIC0gbW9iaWxlCm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiBDb3Jkb3ZhIEFw\
cAogIGNvbnNvbGUub3BlbnNoaWZ0LmlvL2ljb25DbGFzczogZmEgZmEtY29yZG92YQpwbGFuczoK\
ICAtIG5hbWU6IGRlZmF1bHQKICAgIGRlc2NyaXB0aW9uOiBTZXRzIHVwIGEgQ29yZG92YSBBcHAg\
cmVwcmVzZW50YXRpb24uCiAgICBmcmVlOiBUcnVlCiAgICBtZXRhZGF0YToge30KICAgIHBhcmFt\
ZXRlcnM6IAogICAgLSBuYW1lOiBhcHBOYW1lCiAgICAgIHJlcXVpcmVkOiBUcnVlCiAgICAgIGRl\
ZmF1bHQ6IG15YXBwCiAgICAgIHR5cGU6IHN0cmluZwogICAgICB0aXRsZTogeW91ciBuZXcgYXBw\
cyBuYW1lCg=="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
