FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGNvcmRvdmEtYXBwLWFwYgpkZXNjcmlwdGlvbjogU2V0cyB1cCBh\
IENvcmRvdmEgQXBwIHJlcHJlc2VudGF0aW9uLgpiaW5kYWJsZTogRmFsc2UKYXN5bmM6IG9wdGlv\
bmFsCnRhZ3M6IAogIC0gbW9iaWxlCm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiBDb3Jkb3ZhIEFw\
cAogIGNvbnNvbGUub3BlbnNoaWZ0LmlvL2ljb25DbGFzczogZm9udC1pY29uIGljb24tY29yZG92\
YQogIGltYWdlVXJsOiAiaW1hZ2VzL2xvZ29zL2NvcmRvdmEucG5nIgpwbGFuczoKICAtIG5hbWU6\
IGRlZmF1bHQKICAgIGRlc2NyaXB0aW9uOiBTZXRzIHVwIGEgQ29yZG92YSBBcHAgcmVwcmVzZW50\
YXRpb24uCiAgICBmcmVlOiBUcnVlCiAgICBtZXRhZGF0YToge30KICAgIHBhcmFtZXRlcnM6CiAg\
ICAtIG5hbWU6IGFwcE5hbWUKICAgICAgcmVxdWlyZWQ6IFRydWUKICAgICAgZGVmYXVsdDogbXlh\
cHAKICAgICAgdHlwZTogc3RyaW5nCiAgICAgIHRpdGxlOiBBcHBsaWNhdGlvbiBOYW1lCiAgICAt\
IG5hbWU6IGFwcElkZW50aWZpZXIKICAgICAgcmVxdWlyZWQ6IFRydWUKICAgICAgdHlwZTogc3Ry\
aW5nCiAgICAgIHRpdGxlOiBQYWNrYWdlIE5hbWUK"

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
COPY mobile /usr/bin
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
